CREATE TABLE `AutoNorms2020` (
  `motorId` int(11) unsigned NOT NULL COMMENT 'Идентификатор двигателя',
  `modelId` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'Идентификатор модели',
  `carId` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'Идентификатор модификации',
  `typeId` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'Идентификатор типа транспортного средства',
  `make` varchar(100) CHARACTER SET utf8mb4 DEFAULT '' COMMENT 'Марка',
  `model` varchar(100) CHARACTER SET utf8mb4 DEFAULT '' COMMENT 'Модель',
  `litres` varchar(20) CHARACTER SET utf8mb4 DEFAULT '' COMMENT 'Объем двигателя, литр',
  `fuel` varchar(10) CHARACTER SET utf8mb4 DEFAULT '' COMMENT 'Вид топлива',
  `silovoyAgregat` varchar(100) CHARACTER SET utf8mb4 DEFAULT '' COMMENT 'Силовой агрегат',
  `module` varchar(10) CHARACTER SET utf8mb4 DEFAULT '' COMMENT 'Код',
  `engineSalesName` varchar(100) CHARACTER SET utf8mb4 DEFAULT '' COMMENT 'Маркетинговое название двигателя',
  `engineType` varchar(50) CHARACTER SET utf8mb4 DEFAULT '' COMMENT 'Тип двигателя',
  `engineCode` varchar(100) CHARACTER SET utf8mb4 DEFAULT '' COMMENT 'Код двигателя',
  `modification_name` varchar(255) CHARACTER SET utf8mb4 DEFAULT '' COMMENT 'Название модификации',
  `year` varchar(50) CHARACTER SET utf8mb4 DEFAULT '' COMMENT 'Года выпуска транспортного средства',
  `id` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`,`modelId`,`motorId`,`carId`,`typeId`),
  UNIQUE KEY `motorId` (`motorId`) USING BTREE,
  KEY `modelId` (`modelId`,`carId`,`typeId`),
  KEY `make` (`make`),
  KEY `make_2` (`make`,`model`),
  KEY `engineCode` (`engineCode`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Таблица "Транспортные средства" базы "АвтоНормы 2020". Издано 18.01.2020 @ Copyright (c) AUTODATABASES.RU\r\nКлючевое поле для связи с таблицей "Нормы времени" - motorId.\r\n\r\n1. Пример запроса к базе данных mySQL "Показать всех производителей":\r\nSELECT distinct AutoNorms2020.make FROM AutoNorms2020\r\n\r\n2. Пример запроса к базе данных mySQL "Показать все модели BMW":\r\nSELECT distinct AutoNorms2020.motorId, AutoNorms2020.modelId, AutoNorms2020.carId, AutoNorms2020.make, AutoNorms2020.model, AutoNorms2020.`year`, AutoNorms2020.fuel, AutoNorms2020.engineSalesName, AutoNorms2020.modification_name FROM AutoNorms2020 WHERE AutoNorms2020.make = ''BMW''\r\n\r\n3. Пример запроса к базе данных mySQL "Показать нормы времени для транспортного средства с идентификатором двигателя - 1":\r\nSELECT * FROM autoNorms2020Data WHERE autoNorms2020Data.motorId = 1\r\n\r\n';